# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all$fill$localip$time$line_break$shell$character"""

# Inserts a blank line between shell prompts
add_newline = true

[fill]
symbol = ' '

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[directory]
truncation_length = 2

[nodejs]
format = '[$symbol($version )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
format = '[$symbol($version )]($style)'
detect_variables = []

[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'

[localip]
ssh_only = false
format = '[$localipv4](bold green) '
disabled = false
