import = [
  "~/dotfiles/.config/alacritty/dracula.toml",
  "~/dotfiles/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
option_as_alt = "OnlyLeft" # tmux - meta key
# opacity = 0.9

dimensions = { columns = 80, lines = 24 }
padding = { x = 10, y = 5 }

[cursor]
style = { shape = "Beam" }

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Regular Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"
