import = [
  "~/dotfiles/.config/alacritty/dracula.toml",
  "~/dotfiles/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 18.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Regular Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"
